import {
  METRIC_FIELDS,
  METRIC_FIELD_LABELS,
  normalizeCardMetrics,
  sumCardMetrics,
  countMetricsContentTypes,
  formatYearMonthLabel,
} from './cardMetrics';
import { isOneOffProjectCard } from '../constants';

const PDF_MARGIN = 14;
const PDF_PAGE_W = 297;

const PDF_SINGLE_LINE = {
  font: 'helvetica',
  fontSize: 8.5,
  cellPadding: { top: 4, right: 3, bottom: 4, left: 3 },
  lineColor: [200, 200, 200],
  lineWidth: 0.1,
  overflow: 'ellipsize',
  valign: 'middle',
  minCellHeight: 10,
  textColor: [26, 26, 26],
};

function publishDateLabel(card) {
  if (isOneOffProjectCard(card)) {
    return String(card.dueDate || card.shootDate || '—');
  }
  return String(card.dueDate || '—');
}

function drawPdfFooter(doc, pageNumber) {
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by Medici Social · ${new Date().toLocaleString()}`,
    PDF_MARGIN,
    pageH - 8,
  );
  doc.text(`Page ${pageNumber}`, PDF_PAGE_W - PDF_MARGIN, pageH - 8, { align: 'right' });
}

function drawPdfHeader(doc, { monthKey, clientFilter }) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(124, 58, 237);
  doc.text('Medici Social', PDF_MARGIN, 18);

  doc.setTextColor(17, 17, 17);
  doc.setFontSize(16);
  doc.text('Monthly Metrics', PDF_MARGIN, 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const clientLabel =
    clientFilter && clientFilter !== 'all' ? clientFilter : 'All clients';
  doc.text(`${formatYearMonthLabel(monthKey)} · ${clientLabel}`, PDF_MARGIN, 36);

  return 44;
}

function drawPdfSectionTitle(doc, y, title) {
  if (y > doc.internal.pageSize.getHeight() - 36) {
    doc.addPage();
    y = PDF_MARGIN + 4;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(title.toUpperCase(), PDF_MARGIN, y);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGIN, y + 2, PDF_PAGE_W - PDF_MARGIN, y + 2);
  return y + 9;
}

function addOverviewTable(doc, autoTable, startY, contentCounts, engagement) {
  let y = drawPdfSectionTitle(doc, startY, 'This month overview — content mix');

  autoTable(doc, {
    startY: y,
    head: [['Reels', 'Carousels / Statics', 'Total posts']],
    body: [[
      String(contentCounts.reels),
      String(contentCounts.carouselStatics),
      String(contentCounts.total),
    ]],
    theme: 'grid',
    styles: PDF_SINGLE_LINE,
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: 'bold',
      fontSize: 8,
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => drawPdfFooter(doc, data.pageNumber),
  });

  y = doc.lastAutoTable.finalY + 10;
  y = drawPdfSectionTitle(doc, y, 'Engagement overview');

  autoTable(doc, {
    startY: y,
    head: [METRIC_FIELDS.map((field) => METRIC_FIELD_LABELS[field])],
    body: [METRIC_FIELDS.map((field) => String(engagement[field] || 0))],
    theme: 'grid',
    styles: PDF_SINGLE_LINE,
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: 'bold',
      fontSize: 8,
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => drawPdfFooter(doc, data.pageNumber),
  });

  return doc.lastAutoTable.finalY + 10;
}

function addPostsTable(doc, autoTable, startY, cards) {
  let y = drawPdfSectionTitle(doc, startY, 'Each post broken down');

  const head = [
    'Title',
    'Client',
    'Type',
    'Publish date',
    ...METRIC_FIELDS.map((field) => METRIC_FIELD_LABELS[field]),
  ];

  const body = cards.length
    ? cards.map((card) => {
        const metrics = normalizeCardMetrics(card);
        return [
          card.title || '—',
          card.client || '—',
          card.contentType || '—',
          publishDateLabel(card),
          ...METRIC_FIELDS.map((field) => String(metrics[field] || 0)),
        ];
      })
    : [['No dated calendar posts this month.', '', '', '', '', '', '', '', '', '']];

  autoTable(doc, {
    startY: y,
    head: [head],
    body,
    theme: 'grid',
    styles: { ...PDF_SINGLE_LINE, fontSize: 7.5 },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: 'bold',
      fontSize: 7.5,
    },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => drawPdfFooter(doc, data.pageNumber),
  });

  return doc.lastAutoTable.finalY;
}

export function buildMetricsPdfFilename(monthKey) {
  return `metrics-${monthKey || 'month'}.pdf`;
}

export async function downloadMetricsPdf({
  cards = [],
  monthKey,
  clientFilter = 'all',
} = {}) {
  const { jsPDF } = await import('jspdf');
  const { autoTable } = await import('jspdf-autotable');

  const contentCounts = countMetricsContentTypes(cards);
  const engagement = sumCardMetrics(cards);

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  let y = drawPdfHeader(doc, { monthKey, clientFilter });
  y = addOverviewTable(doc, autoTable, y, contentCounts, engagement);
  addPostsTable(doc, autoTable, y, cards);

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    drawPdfFooter(doc, i);
  }

  doc.save(buildMetricsPdfFilename(monthKey));
  return doc;
}
