import { getStructuredScript } from './scriptFields';
import {
  isSlidePostType,
  PER_SLIDE_CAPTION_MODE,
  SHARED_CAPTION_MODE,
} from './postSlides';

const PDF_MARGIN = 14;
const PDF_PAGE_W = 210; // A4 portrait

const PDF_BODY = {
  font: 'helvetica',
  fontSize: 10,
  cellPadding: { top: 5, right: 4, bottom: 5, left: 4 },
  lineColor: [200, 200, 200],
  lineWidth: 0.1,
  overflow: 'linebreak',
  valign: 'top',
  textColor: [26, 26, 26],
};

function safeSlug(value, fallback = 'card') {
  const slug = String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return slug || fallback;
}

export function buildScriptPdfFilename(card = {}) {
  const client = safeSlug(card.client, 'client');
  const title = safeSlug(card.title, 'script');
  return `script-${client}-${title}.pdf`;
}

function displayOrDash(value) {
  const text = String(value || '').trim();
  return text || '—';
}

/**
 * Pure section builder for tests and PDF rendering.
 * Returns [{ title, body }] blocks in reading order.
 */
export function buildScriptPdfSections(card = {}) {
  const script = getStructuredScript(card);
  const sections = [];

  if (isSlidePostType(card.contentType)) {
    const slides = script.postSlides || [];
    slides.forEach((slide, index) => {
      const media = slide.mediaType === 'video' ? 'Video' : 'Photo';
      const lines = [
        `Media: ${media}`,
        '',
        'Description',
        displayOrDash(slide.description),
        '',
        'Text overlay',
        displayOrDash(slide.textOverlay),
      ];
      if (script.captionMode === PER_SLIDE_CAPTION_MODE) {
        lines.push('', 'Caption', displayOrDash(slide.caption));
      }
      sections.push({
        title: `Slide ${index + 1}`,
        body: lines.join('\n'),
      });
    });

    if (script.captionMode === SHARED_CAPTION_MODE || card.contentType === 'Static Post') {
      sections.push({
        title: 'Caption',
        body: displayOrDash(script.caption),
      });
    }

    return sections;
  }

  sections.push({ title: 'Hook', body: displayOrDash(script.hook) });
  sections.push({ title: 'Body', body: displayOrDash(script.body) });
  sections.push({ title: 'Text overlays', body: displayOrDash(script.overlays) });
  sections.push({ title: 'Caption', body: displayOrDash(script.caption) });
  return sections;
}

function drawPdfFooter(doc, pageNumber) {
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by Medici Social · ${new Date().toLocaleString()}`,
    PDF_MARGIN,
    pageH - 8,
  );
  doc.text(`Page ${pageNumber}`, PDF_PAGE_W - PDF_MARGIN, pageH - 8, { align: 'right' });
}

function drawPdfHeader(doc, card) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(124, 58, 237);
  doc.text('Medici Social', PDF_MARGIN, 18);

  doc.setTextColor(17, 17, 17);
  doc.setFontSize(16);
  const heading = isSlidePostType(card?.contentType) ? 'Slide Plan' : 'Shoot Script';
  doc.text(heading, PDF_MARGIN, 28);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(String(card?.title || 'Untitled').trim() || 'Untitled', PDF_MARGIN, 36);

  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  const meta = [
    card?.client || null,
    card?.contentType || null,
    card?.dueDate ? `Publish ${card.dueDate}` : null,
    card?.shootDate ? `Shoot ${card.shootDate}` : null,
  ]
    .filter(Boolean)
    .join(' · ');
  if (meta) {
    doc.text(meta, PDF_MARGIN, 42);
  }

  return meta ? 50 : 44;
}

function drawPdfSectionTitle(doc, y, title) {
  const pageH = doc.internal.pageSize.getHeight();
  if (y > pageH - 40) {
    doc.addPage();
    y = PDF_MARGIN + 4;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(String(title).toUpperCase(), PDF_MARGIN, y);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGIN, y + 2, PDF_PAGE_W - PDF_MARGIN, y + 2);
  return y + 9;
}

function addTextSection(doc, autoTable, startY, title, body) {
  let y = drawPdfSectionTitle(doc, startY, title);

  autoTable(doc, {
    startY: y,
    body: [[body]],
    theme: 'grid',
    styles: {
      ...PDF_BODY,
      minCellHeight: 12,
    },
    columnStyles: {
      0: { cellWidth: PDF_PAGE_W - PDF_MARGIN * 2 },
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => drawPdfFooter(doc, data.pageNumber),
  });

  return doc.lastAutoTable.finalY + 8;
}

export async function downloadScriptPdf(card = {}) {
  const { jsPDF } = await import('jspdf');
  const { autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = drawPdfHeader(doc, card);

  const sections = buildScriptPdfSections(card);
  for (const section of sections) {
    y = addTextSection(doc, autoTable, y, section.title, section.body);
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    drawPdfFooter(doc, i);
  }

  doc.save(buildScriptPdfFilename(card));
  return doc;
}
