import {
  buildShootTimeline,
  aggregateModelsWithSlots,
  formatModelScheduleLines,
  aggregateNeeds,
  formatTimeInput,
  formatShootDayLabel,
  parseDateKey,
  parseTimeToMinutes,
} from "./shootDay";

const A4_WIDTH_PX = 794;

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function empty(value) {
  return value ? escapeHtml(value) : "—";
}

function productionStyles() {
  return `
    @page { size: A4 landscape; margin: 12mm; }
    * { box-sizing: border-box; }
    html, body {
      width: ${A4_WIDTH_PX}px;
      margin: 0;
      padding: 0;
      background: #fff;
      color: #1a1a1a;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.5;
    }
    .sheet { width: 100%; padding: 28px 32px 36px; }
    .avoid-break { page-break-inside: avoid; break-inside: avoid; }
    .section { margin-top: 24px; }
    .section-title {
      font-size: 9pt;
      font-weight: 700;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #666;
      border-bottom: 1px solid #ddd;
      padding-bottom: 6px;
      margin: 0 0 12px;
    }
    .simple-header { margin-bottom: 20px; }
    .brand { color: #7c3aed; font-size: 10pt; font-weight: 700; margin: 0 0 8px; }
    .sheet-title { font-size: 20pt; font-weight: 700; margin: 0 0 6px; }
    .subtitle { color: #555; margin: 0; }
    .meta { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
    .meta th {
      text-align: left;
      width: 140px;
      color: #666;
      font-weight: 600;
      padding: 8px 12px 8px 0;
      vertical-align: top;
    }
    .meta td { padding: 8px 0; white-space: nowrap; }
    table.schedule {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }
    table.schedule th, table.schedule td {
      border: 1px solid #ddd;
      padding: 10px 12px;
      text-align: left;
      vertical-align: middle;
      font-size: 10pt;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    table.schedule th {
      background: #f5f5f5;
      font-size: 9pt;
      font-weight: 700;
      color: #444;
    }
    table.schedule .col-time { width: 90px; font-weight: 600; }
    table.schedule tr:nth-child(even) td { background: #fafafa; }
    .list-block {
      border: 1px solid #ddd;
      padding: 14px 16px;
    }
    .list-block .label {
      font-size: 9pt;
      font-weight: 700;
      color: #666;
      margin-bottom: 8px;
    }
    .list-block li {
      padding: 4px 0;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
    .notes-box {
      border: 1px solid #ddd;
      padding: 14px 16px;
      background: #fafafa;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .footer {
      margin-top: 28px;
      padding-top: 12px;
      border-top: 1px solid #eee;
      color: #999;
      font-size: 9pt;
    }
  `;
}

function simpleHeader({ title, client, dateLabel }) {
  return `
    <header class="simple-header avoid-break">
      <p class="brand">Medici Social</p>
      <h1 class="sheet-title">${escapeHtml(title)}</h1>
      <p class="subtitle"><strong>${escapeHtml(client)}</strong> · ${escapeHtml(dateLabel)}</p>
    </header>`;
}

function sessionInfoGrid(plan) {
  const windowLabel =
    plan.shootStartTime && plan.shootEndTime
      ? `${formatTimeInput(plan.shootStartTime)} – ${formatTimeInput(plan.shootEndTime)}`
      : "—";

  return `
    <table class="meta avoid-break">
      ${row("Location", plan.location)}
      ${row("Shoot window", windowLabel !== "—" ? windowLabel : "")}
    </table>`;
}

function scheduleTableHead() {
  return `
    <thead>
      <tr>
        <th>Time</th>
        <th>Type</th>
        <th>Title</th>
        <th>Models / talent</th>
        <th>Props &amp; needs</th>
      </tr>
    </thead>`;
}

function scheduleTableRow(entry, options = {}) {
  const { tbd = false, outside = false } = options;
  const card = entry.card || entry;
  const timeLabel = entry.startLabel || "TBD";

  return `
    <tr class="avoid-break">
      <td class="col-time">${escapeHtml(timeLabel)}</td>
      <td>${escapeHtml(card.contentType)}</td>
      <td>${escapeHtml(card.title)}${outside ? " (Outside window)" : ""}</td>
      <td>${empty(card.shootModels)}</td>
      <td>${empty(card.shootNeeds)}</td>
    </tr>`;
}

function simpleFooter() {
  return `
    <footer class="footer avoid-break">
      <span>Generated by Medici Social · ${escapeHtml(new Date().toLocaleString())}</span>
    </footer>`;
}

function listBlock(label, items) {
  if (!items.length) {
    return `
      <div class="list-block avoid-break">
        <div class="label">${escapeHtml(label)}</div>
        <p style="margin:0;color:#999;">—</p>
      </div>`;
  }
  return `
    <div class="list-block avoid-break">
      <div class="label">${escapeHtml(label)}</div>
      <ul style="margin:0;padding:0;list-style:none;">${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
    </div>`;
}

function wrapDocument(title, body) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>${productionStyles()}</style>
</head>
<body>
  <div class="sheet">${body}</div>
</body>
</html>`;
}

function buildModelCallTimeRows(modelSchedules) {
  const rows = [];

  for (const { name, slots } of modelSchedules) {
    for (const slot of slots) {
      const content = slot.contentTitle
        ? `${slot.contentTitle}${slot.contentType ? ` · ${slot.contentType}` : ""}`
        : "—";
      rows.push([name, slot.timeLabel, content]);
    }
  }

  if (!rows.length) {
    rows.push(["—", "—", "No models added yet."]);
  }

  return rows;
}

function modelCallTimesHtml(modelSchedules) {
  const rows = buildModelCallTimeRows(modelSchedules);

  return `
    <section class="section avoid-break">
      <h2 class="section-title">Model call times</h2>
      <table class="schedule model-call-times">
        <thead>
          <tr>
            <th>Model</th>
            <th>Time</th>
            <th>Content</th>
          </tr>
        </thead>
        <tbody>
          ${rows
            .map(
              ([model, time, content]) => `
            <tr class="avoid-break">
              <td>${escapeHtml(model)}</td>
              <td class="col-time">${escapeHtml(time)}</td>
              <td>${escapeHtml(content)}</td>
            </tr>`,
            )
            .join("")}
        </tbody>
      </table>
    </section>`;
}

export function buildShootPrintPayload({ client, dateKey, plan, cards }) {
  const focusDate = parseDateKey(dateKey);
  const timeline = buildShootTimeline(cards);
  const modelSchedules = aggregateModelsWithSlots(cards, plan.sessionModels, plan);
  const allModels = formatModelScheduleLines(modelSchedules);
  const allNeeds = aggregateNeeds(cards, plan.sessionNeeds);
  const scheduledIds = new Set(timeline.map((e) => e.card.id));
  const unscheduled = cards.filter((c) => !scheduledIds.has(c.id));

  return {
    client,
    dateKey,
    dateLabel: formatShootDayLabel(focusDate),
    plan,
    cards: [...timeline.map((e) => e.card), ...unscheduled],
    timeline,
    modelSchedules,
    allModels,
    allNeeds,
    unscheduled,
  };
}

export function buildShootPrintHtml(payload) {
  const { client, dateLabel, plan, timeline, modelSchedules, allNeeds, unscheduled } = payload;

  let shotNum = 0;
  const scheduledRows = timeline
    .map((entry) => scheduleTableRow(entry))
    .join("");

  const unscheduledRows = unscheduled
    .map((card) => scheduleTableRow({ card, startLabel: "TBD" }, { tbd: true }))
    .join("");

  const bodyRows =
    scheduledRows || unscheduledRows
      ? scheduledRows + unscheduledRows
      : `<tr><td colspan="5" style="padding:16px 12px;color:#888;">No shoot times assigned yet.</td></tr>`;

  const body = `
    ${simpleHeader({
      title: "Shoot Schedule",
      client,
      dateLabel,
    })}
    <section class="section">
      <h2 class="section-title">Session</h2>
      ${sessionInfoGrid(plan)}
    </section>
    <section class="section">
      <h2 class="section-title">Content schedule</h2>
      <table class="schedule">
        ${scheduleTableHead()}
        <tbody>${bodyRows}</tbody>
      </table>
    </section>
    ${modelCallTimesHtml(modelSchedules)}
    <section class="section">
      ${listBlock("Equipment & needs", allNeeds)}
    </section>
    ${
      plan.notes
        ? `<section class="section avoid-break"><h2 class="section-title">Session notes</h2><div class="notes-box">${escapeHtml(plan.notes)}</div></section>`
        : ""
    }
    ${simpleFooter()}`;

  return wrapDocument(`${client} — Shoot Schedule`, body);
}

export function buildTimelineRowsPrintHtml(payload) {
  const { client, dateLabel, plan, timeline, modelSchedules, unscheduled } = payload;
  const windowStart = parseTimeToMinutes(plan?.shootStartTime);
  const windowEnd = parseTimeToMinutes(plan?.shootEndTime);

  const scheduledRows = timeline
    .map((entry) => {
      const outside =
        windowStart != null &&
        windowEnd != null &&
        (entry.startMinutes < windowStart || entry.endMinutes > windowEnd);
      return scheduleTableRow(entry, { outside });
    })
    .join("");

  const unscheduledRows = unscheduled
    .map((card) => scheduleTableRow({ card, startLabel: "TBD" }, { tbd: true }))
    .join("");

  const bodyRows =
    scheduledRows || unscheduledRows
      ? scheduledRows + unscheduledRows
      : `<tr><td colspan="5" style="padding:16px 12px;color:#888;">No shoot times assigned yet.</td></tr>`;

  const body = `
    ${simpleHeader({
      title: "Shoot Schedule Timeline",
      client,
      dateLabel,
    })}
    <section class="section">
      <h2 class="section-title">Session</h2>
      ${sessionInfoGrid(plan)}
    </section>
    <section class="section">
      <h2 class="section-title">Schedule by time</h2>
      <table class="schedule">
        ${scheduleTableHead()}
        <tbody>${bodyRows}</tbody>
      </table>
    </section>
    ${modelCallTimesHtml(modelSchedules)}
    ${simpleFooter()}`;

  return wrapDocument(`${client} — Shoot Timeline`, body);
}

export function printShootSchedule(payload) {
  openPrintWindow(buildShootPrintHtml(payload));
}

export function printTimelineRows(payload) {
  openPrintWindow(buildTimelineRowsPrintHtml(payload));
}

function buildPdfFilename(client, dateKey, label) {
  const safeClient = String(client).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "");
  return `${safeClient}-${dateKey}-${label}.pdf`;
}

const PDF_MARGIN = 14;
const PDF_PAGE_W = 297;

function buildShotTableRows(payload) {
  const { timeline, unscheduled, plan } = payload;
  const windowStart = parseTimeToMinutes(plan?.shootStartTime);
  const windowEnd = parseTimeToMinutes(plan?.shootEndTime);
  const rows = [];

  for (const entry of timeline) {
    const outside =
      windowStart != null &&
      windowEnd != null &&
      (entry.startMinutes < windowStart || entry.endMinutes > windowEnd);
    const title = outside ? `${entry.card.title} (Outside window)` : entry.card.title;
    rows.push([
      entry.startLabel,
      entry.card.contentType,
      title,
      entry.card.shootModels || "—",
      entry.card.shootNeeds || "—",
    ]);
  }

  for (const card of unscheduled) {
    rows.push(["TBD", card.contentType, card.title, card.shootModels || "—", card.shootNeeds || "—"]);
  }

  if (!rows.length) {
    rows.push(["", "", "No shoot times assigned yet.", "", ""]);
  }

  return rows;
}

const PDF_TABLE_HEAD = [["Time", "Type", "Title", "Models / talent", "Props & needs"]];

const PDF_SINGLE_LINE = {
  font: "helvetica",
  fontSize: 9,
  cellPadding: { top: 5, right: 4, bottom: 5, left: 4 },
  lineColor: [200, 200, 200],
  lineWidth: 0.1,
  overflow: "ellipsize",
  valign: "middle",
  minCellHeight: 11,
  textColor: [26, 26, 26],
};

function drawPdfFooter(doc, pageNumber) {
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by Medici Social · ${new Date().toLocaleString()}`,
    PDF_MARGIN,
    pageH - 8,
  );
  doc.text(`Page ${pageNumber}`, PDF_PAGE_W - PDF_MARGIN, pageH - 8, { align: "right" });
}

function drawPdfHeader(doc, { title, client, dateLabel }) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(124, 58, 237);
  doc.text("Medici Social", PDF_MARGIN, 18);

  doc.setTextColor(17, 17, 17);
  doc.setFontSize(16);
  doc.text(title, PDF_MARGIN, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`${client} · ${dateLabel}`, PDF_MARGIN, 36);

  return 44;
}

function drawPdfSessionTable(doc, autoTable, startY, plan) {
  const windowLabel =
    plan.shootStartTime && plan.shootEndTime
      ? `${formatTimeInput(plan.shootStartTime)} – ${formatTimeInput(plan.shootEndTime)}`
      : "—";

  autoTable(doc, {
    startY,
    head: [["Location", "Shoot window"]],
    body: [[
      plan.location || "—",
      windowLabel,
    ]],
    theme: "grid",
    styles: {
      ...PDF_SINGLE_LINE,
      fontSize: 9.5,
      minCellHeight: 12,
    },
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: { top: 5, right: 4, bottom: 5, left: 4 },
    },
    columnStyles: {
      0: { cellWidth: (PDF_PAGE_W - PDF_MARGIN * 2) / 3 },
      1: { cellWidth: (PDF_PAGE_W - PDF_MARGIN * 2) / 3 },
      2: { cellWidth: (PDF_PAGE_W - PDF_MARGIN * 2) / 3 },
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
  });

  return doc.lastAutoTable.finalY + 10;
}

function drawPdfSectionTitle(doc, y, title) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(title.toUpperCase(), PDF_MARGIN, y);
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGIN, y + 2, PDF_PAGE_W - PDF_MARGIN, y + 2);
  return y + 9;
}

function addPdfShotTable(doc, autoTable, startY, bodyRows) {
  const tableWidth = PDF_PAGE_W - PDF_MARGIN * 2;

  autoTable(doc, {
    startY,
    head: PDF_TABLE_HEAD,
    body: bodyRows,
    theme: "grid",
    styles: PDF_SINGLE_LINE,
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: { top: 6, right: 4, bottom: 6, left: 4 },
      overflow: "ellipsize",
    },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    columnStyles: {
      0: { cellWidth: tableWidth * 0.11, overflow: "ellipsize" },
      1: { cellWidth: tableWidth * 0.12, overflow: "ellipsize" },
      2: { cellWidth: tableWidth * 0.33, overflow: "ellipsize" },
      3: { cellWidth: tableWidth * 0.22, overflow: "ellipsize" },
      4: { cellWidth: tableWidth * 0.22, overflow: "ellipsize" },
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, top: PDF_MARGIN, bottom: 14 },
    rowPageBreak: "avoid",
    showHead: "everyPage",
    didDrawPage: (data) => {
      drawPdfFooter(doc, data.pageNumber);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function addPdfModelCallTimesTable(doc, autoTable, startY, modelSchedules) {
  let y = startY;

  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = PDF_MARGIN + 4;
  }

  y = drawPdfSectionTitle(doc, y, "Model call times");

  const tableWidth = PDF_PAGE_W - PDF_MARGIN * 2;

  autoTable(doc, {
    startY: y,
    head: [["Model", "Time", "Content"]],
    body: buildModelCallTimeRows(modelSchedules),
    theme: "grid",
    styles: PDF_SINGLE_LINE,
    headStyles: {
      fillColor: [245, 245, 245],
      textColor: [60, 60, 60],
      fontStyle: "bold",
      fontSize: 8,
      cellPadding: { top: 6, right: 4, bottom: 6, left: 4 },
      overflow: "ellipsize",
    },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    columnStyles: {
      0: { cellWidth: tableWidth * 0.22, overflow: "ellipsize" },
      1: { cellWidth: tableWidth * 0.28, overflow: "ellipsize" },
      2: { cellWidth: tableWidth * 0.5, overflow: "ellipsize" },
    },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, top: PDF_MARGIN, bottom: 14 },
    rowPageBreak: "avoid",
    showHead: "everyPage",
    didDrawPage: (data) => {
      drawPdfFooter(doc, data.pageNumber);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function addPdfListSection(doc, autoTable, startY, title, items) {
  let y = startY;

  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = PDF_MARGIN + 4;
  }

  y = drawPdfSectionTitle(doc, y, title);

  const body = items.length ? items.map((item) => [item]) : [["—"]];

  autoTable(doc, {
    startY: y,
    body,
    theme: "grid",
    styles: {
      ...PDF_SINGLE_LINE,
      fontSize: 9.5,
      minCellHeight: 11,
    },
    columnStyles: { 0: { cellWidth: PDF_PAGE_W - PDF_MARGIN * 2, overflow: "ellipsize" } },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => {
      drawPdfFooter(doc, data.pageNumber);
    },
  });

  return doc.lastAutoTable.finalY + 10;
}

function addPdfNotes(doc, autoTable, startY, notes) {
  let y = startY;
  if (y > doc.internal.pageSize.getHeight() - 36) {
    doc.addPage();
    y = PDF_MARGIN + 4;
  }

  y = drawPdfSectionTitle(doc, y, "Session notes");

  autoTable(doc, {
    startY: y,
    body: [[notes]],
    theme: "grid",
    styles: {
      ...PDF_SINGLE_LINE,
      fontSize: 9.5,
      minCellHeight: 12,
    },
    columnStyles: { 0: { cellWidth: PDF_PAGE_W - PDF_MARGIN * 2, overflow: "ellipsize" } },
    margin: { left: PDF_MARGIN, right: PDF_MARGIN, bottom: 14 },
    didDrawPage: (data) => {
      drawPdfFooter(doc, data.pageNumber);
    },
  });

  return doc.lastAutoTable.finalY;
}

async function createProductionPdf(payload, variant) {
  const { jsPDF } = await import("jspdf");
  const { autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const isFull = variant === "full";

  let y = drawPdfHeader(doc, {
    title: isFull ? "Shoot Schedule" : "Shoot Schedule Timeline",
    client: payload.client,
    dateLabel: payload.dateLabel,
  });

  y = drawPdfSectionTitle(doc, y, "Session");
  y = drawPdfSessionTable(doc, autoTable, y, payload.plan);
  y = drawPdfSectionTitle(doc, y, isFull ? "Content schedule" : "Schedule by time");
  y = addPdfShotTable(doc, autoTable, y, buildShotTableRows(payload));
  y = addPdfModelCallTimesTable(doc, autoTable, y, payload.modelSchedules);

  if (isFull) {
    y = addPdfListSection(doc, autoTable, y, "Equipment & needs", payload.allNeeds);
    if (payload.plan.notes) {
      addPdfNotes(doc, autoTable, y, payload.plan.notes);
    }
  }

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    drawPdfFooter(doc, i);
  }

  return doc;
}

export async function downloadShootSchedule(payload) {
  const doc = await createProductionPdf(payload, "full");
  doc.save(buildPdfFilename(payload.client, payload.dateKey, "shoot-schedule"));
}

export async function downloadTimelineRows(payload) {
  const doc = await createProductionPdf(payload, "timeline");
  doc.save(buildPdfFilename(payload.client, payload.dateKey, "shoot-timeline"));
}

function openPrintWindow(html) {
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) {
    window.alert("Please allow pop-ups to print or save as PDF.");
    return;
  }
  win.document.open();
  win.document.write(html);
  win.document.close();
  win.onload = () => {
    win.focus();
    win.print();
  };
}
